config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'diablo#index'

  get 'diablo/search'

  get 'location/region'
  get 'location/locale'

  get 'shared/search'

  get 'career/index'

  get 'hero/index'

  get 'compare/index'
  get 'compare/career'
  get 'compare/hero'

  get 'build/index'

  get 'forum/index'

  get 'impressum/index'
  mount I18nTranslation::Engine => "/i18n_translation"
end

app/models/hero.rb
class Hero < ActiveRecord::Base
  belongs_to :career

  serialize :name
  serialize :class
  serialize :gender
  serialize :level
  serialize :kills
  serialize :paragon_level
  serialize :hardcore
  serialize :seasonal
  serialize :season_created
  serialize :skills
  serialize :items
  serialize :followers
  serialize :legendary_powers
  serialize :stats
  serialize :progression
  serialize :dead
  serialize :last_updated
end

app/controllers/hero_controller.rb
class HeroController < ApplicationController
  include DiabloDataHelper

  def index
    @career = process_diablodata(session[:region], session[:locale], params[:battle_tag])
    @hero = process_diablodata(session[:region], session[:locale], params[:battle_tag], params[:hero_id])
    @portrait = DiabloApi::Icons::Portrait
    @paperdoll = DiabloApi::Icons::Paperdoll
    @item = DiabloApi::Icons::Item
    @tooltip = DiabloApi::Tooltip
  end
end

app/helpers/hero_helper.rb
module HeroHelper
end

app/views/hero/index.html.erb
<%= javascript_include_tag "http://us.battle.net/d3/static/js/tooltips.js", "data-turbolinks-track" => true %>

<table class="portrait centered">
  <tr>
    <% @career.heroes.each do |h| %>
    <td class="center">
      <%= link_to image_tag(@portrait.middle(h[:class], h[:gender])), hero_index_path(hero_id: h[:id], battle_tag: @career.battle_tag) %>
    </td>
    <td class="center">
      <div class="name">
        <%= link_to h[:name], hero_index_path(hero_id: h[:id], battle_tag: @career.battle_tag) %>
      </div>
      <div class="hardcore">
        <% if h[:hardcore] %>
        <div class="red">Hardcore</div>
        <% end %>
      </div>
      <div class="seasonal">
        <% if h[:seasonal] %>
        <span class="small-seasonal-leaf"></span>
        <% end %>
      </div>
    </td>
    <% end %>
  </tr>
</table>
<div class="row">
  <h2>
    <%= @hero.hero_class %>
  </h2>
  <div class="row">
    <div class="col-lg-3">
      <div class="stats">
        <%= render 'shared/hero_stats', stats: @hero.stats %>
      </div>
    </div>
    <div class="col-lg-6">
      <div class="absolut-position" id="name">
        <h1>
          <%= @hero.name %>
        </h1>
      </div>

      <%= image_tag @paperdoll.original(session[:region], @hero.hero_class, @hero.gender) %>
      <table>
        <% @hero.items.each do |item| %>
        <tr>
          <th>
            <%= link_to (image_tag @item.large(item[1][:icon]), class: "#{item[0]} absolut-position"), @tooltip.tooltip_url(session[:region], session[:locale_short], item[1][:tooltip_params]).sub('/tooltip', '') ,data: {d3tooltip: @tooltip.tooltip_url(session[:region], session[:locale_short], item[1][:tooltip_params])+'?format=jsonp'}, target: '_blank' %>
          </th>
        </tr>
        <% end %>
      </table>
    </div>
    <div class="col-lg-3">

      <%= render 'shared/skill', skill: @hero[:skills][:active] %>

    </div>
  </div>
</div>