config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'diablo#index'

  get 'diablo/search'

  get 'location/region'
  get 'location/locale'

  get 'shared/search'

  get 'career/index'

  get 'hero/index'

  get 'compare/index'
  get 'compare/career'
  get 'compare/hero'

  get 'build/index'

  get 'forum/index'

  get 'impressum/index'
  mount I18nTranslation::Engine => "/i18n_translation"
end

app/controllers/compare_controller.rb
class CompareController < ApplicationController

  def index

  end

  def career
    session[:battle_tag] = params[:battle_tag]
    session[:battle_tag2] = params[:battle_tag2]
    session[:region] = session[:region]
    session[:locale] = session[:locale]
    session[:language] = session[:locale].match(/(.*)_/)[1]
    @career = DiabloApi::Career.new(session[:region], session[:locale], params[:battle_tag])
    @career2 = DiabloApi::Career.new(session[:region], session[:locale], params[:battle_tag2])
    @portrait = DiabloApi::Icons::Portrait
  end


  def hero
    @career = DiabloApi::Career.new(session[:region], session[:locale], session[:battle_tag])
    @career2 = DiabloApi::Career.new(session[:region], session[:locale], session[:battle_tag2])
    @hero = DiabloApi::Hero.new(session[:region], session[:locale], session[:battle_tag], params[:hero_id])
    @hero2 = DiabloApi::Hero.new(session[:region], session[:locale], session[:battle_tag2], params[:hero_id2])
    @portrait = DiabloApi::Icons::Portrait
    @paperdoll = DiabloApi::Icons::Paperdoll
    @item = DiabloApi::Icons::Item
  end
end

app/helpers/compare_helper.rb
module CompareHelper
end

app/views/compare/_compare_stats.html.erb
<% life = stats['life'] - stats2['life'] %>
<% damage = stats['damage'] - stats2['damage'] %>
<% toughness = stats['toughness'] - stats2['toughness'] %>
<% healing = stats['healing'] - stats2['healing'] %>
<% armor = stats['armor'] - stats2['armor'] %>
<% strength = stats['strength'] - stats2['strength'] %>
<% dexterity = stats['dexterity'] - stats2['dexterity'] %>
<% vitality = stats['vitality'] - stats2['vitality'] %>
<% intelligence = stats['intelligence'] - stats2['intelligence'] %>
<table id="stats">
  <tr>
    <%= render 'compare/get_winner', value: life, name: 'Life' %>
  </tr>
  <tr>
    <%= render 'compare/get_winner', value: damage, name: 'Damage' %>
  </tr>
  <tr>
    <%= render 'compare/get_winner', value: toughness, name: 'Toughness' %>
  </tr>
  <tr>
    <%= render 'compare/get_winner', value: healing, name: 'Healing' %>
  </tr>
  <tr>
    <%= render 'compare/get_winner', value: armor, name: 'Armor' %>
  </tr>
  <tr>
    <%= render 'compare/get_winner', value: strength, name: 'Strength' %>
  </tr>
  <tr>
    <%= render 'compare/get_winner', value: dexterity, name: 'Dexterity' %>
  </tr>
  <tr>
    <%= render 'compare/get_winner', value: vitality, name: 'Vitality' %>
  </tr>
  <tr>
    <%= render 'compare/get_winner', value: intelligence, name: 'Intelligence' %>
  </tr>
</table>

app/views/compare/_get_winner.html.erb
<% if value.round > 0 %>
  <th>
    <i class="fa fa-check"></i>
  </th>
  <th class="left">
    <%= name %>
  </th>
  <th class="right">
    <%= value.round.to_s.gsub(/(\d)(?=(\d\d\d)+(?!\d))/, "\\1 ") %>
  </th>
  <th>
    <i class="fa fa-meh-o"></i>
  </th>
<% elsif value.round < 0 %>
  <th>
    <i class="fa fa-meh-o"></i>
  </th>
  <th class="left">
    <%= name  %>
  </th>
  <th class="right">
    <%= value.round.to_s.gsub(/(\d)(?=(\d\d\d)+(?!\d))/, "\\1 ") %>
  </th>
  <th>
    <i class="fa fa-check"></i>
  </th>
<% else %>
  <th>
    <i class="fa fa-check"></i>
  </th>
  <th class="left">
    <%= name  %>
  </th>
  <th class="right">
    <%= value.round.to_s.gsub(/(\d)(?=(\d\d\d)+(?!\d))/, "\\1 ") %>
  </th>
  <th>
    <i class="fa fa-check"></i>
  </th>
<% end %>

app/views/compare/career.html.erb
<div class="row">
  <%= form_tag(compare_hero_path, method: "get") do %>
    <div class="col-lg-5">
      <%= render 'shared/profil', {career: @career, hero: 'hero_id'} %>
    </div>
    <div class="col-lg-2">
      <%= button_tag "COMPARE", class:'btn btn-default' %>
    </div>
    <div class="col-lg-5">
      <%= render 'shared/profil', {career: @career2, hero: 'hero_id2'} %>
    </div>
  <% end %>
</div>

app/views/compare/hero.html.erb
<div class="row">
  <div class="col-lg-3">
    <h1>
      <%= @hero.name %>
    </h1>
    <%= render 'shared/hero_stats', stats: @hero.stats %>
  </div>
  <div class="col-lg-6">
    <h1>VS.</h1>
    <%= render 'compare/compare_stats', {stats: @hero.stats, stats2: @hero2.stats} %>
    <div class="row">
      <div class="col-lg-6">
        <%= render 'shared/skill', skill: @hero.skills['active'] %>
      </div>
      <div class="col-lg-6">
        <%= render 'shared/skill', skill: @hero2.skills['active'] %>
      </div>
    </div>
  </div>
  <div class="col-lg-3">
    <h1>
      <%= @hero2.name %>
    </h1>
    <%= render 'shared/hero_stats', stats: @hero2.stats %>
  </div>
</div>

app/views/compare/index.html.erb
<div class="row">
  <div class="col-lg-2"></div>
  <div class="col-lg-6 center-block">
    <%= form_tag(compare_career_path, method: "get") do %>
    <div class="input-group input-group-lg">

      <%= text_field_tag :battle_tag, nil, class: 'form-control input-lg', autofocus: true, placeholder: 'Battle Tag 1: Name#Number' %>

      <%= text_field_tag :battle_tag2, nil, class: 'form-control input-lg', placeholder: 'Battle Tag 2: Name#Number' %>
      <span class="input-group-btn">
        <%= button_tag "Search", class: 'btn btn-default btn-lg', remote: true %>
      </span>
    </div>
    <% end %>
  </div>
  <div class="col-lg-2">
    <!-- <%= render 'shared/last_updated' %> -->
  </div>
</div>